language: ruby
cache: bundler
before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.17.3
  - bundler --version
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.5
  - 2.6.3
branches:
  only:
    - master
